add clang-format check action

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,11 +34,13 @@ jobs:
 
       - name: Setup python
         uses: actions/setup-python@v1
-      - name: Run clang-format style check for C/C++/Protobuf programs.
-        uses: jidicula/clang-format-action@v4.11.0
-        with:
-          clang-format-version: '18'
-          check-path: '.'
+      - name: Run clang-format style check
+        run: |
+          git clang-format --diff HEAD~1 -q
+          if git clang-format --diff HEAD~1 -q | grep -m 1 '^' >/dev/null; then
+              echo >&2 "Failed clang-format check. Run: git clang-format HEAD~1"
+          exit 1
+          fi
       - name: Build
         env:
           HCL_COMMUNICATION: ${{ matrix.COMMUNICATION }}
